LOAD THE DATASET

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


df = pd.read_csv('data/ai-dev-data.csv')
df.head()

,User_ID,Day,Experience_Level,AI_Tool_Usage_%,Hours_Coded,Code_Complexity_Score,Bugs_Introduced,Tasks_Completed,Stress_Level_1_10,Current_Burnout_Score,Burnout_Risk
0,DEV_0001,1,Junior,26.7,7.4,5,2,6.98,5,97.0,High
1,DEV_0001,2,Junior,0.0,11.6,3,2,8.35,6,97.0,High
2,DEV_0001,3,Junior,18.7,7.7,9,3,7.11,6,97.0,High
3,DEV_0001,4,Junior,13.0,7.7,7,3,7.10,6,97.0,High
4,DEV_0001,5,Junior,22.8,7.6,6,3,7.05,6,96.5,High

INSPECT THE DATASET

In [3]:
df.shape
# tells (rows x cols)
df.info()
# tells rows , col , count , size
df.describe()
# numerical cols mean , std , max , min)
df.describe(include='object')
# tells about objects cols
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 360000 entries, 0 to 359999
Data columns (total 11 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   User_ID                360000 non-null  str
 1   Day                    360000 non-null  int64
 2   Experience_Level       360000 non-null  str
 3   AI_Tool_Usage_%        360000 non-null  float64
 4   Hours_Coded            360000 non-null  float64
 5   Code_Complexity_Score  360000 non-null  int64
 6   Bugs_Introduced        360000 non-null  int64
 7   Tasks_Completed        360000 non-null  float64
 8   Stress_Level_1_10      360000 non-null  int64
 9   Current_Burnout_Score  360000 non-null  float64
 10  Burnout_Risk           360000 non-null  str
dtypes: float64(4), int64(4), str(3)
memory usage: 30.2 MB

C:\Users\rox\AppData\Local\Temp\ipykernel_19484\2183279537.py:7: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')

User_ID                  0
Day                      0
Experience_Level         0
AI_Tool_Usage_%          0
Hours_Coded              0
Code_Complexity_Score    0
Bugs_Introduced          0
Tasks_Completed          0
Stress_Level_1_10        0
Current_Burnout_Score    0
Burnout_Risk             0
dtype: int64

In [4]:
df[df.isnull().any(axis=1)]
# shows null for row axis
df.nunique()    
# How many different values exist in that feature.
# We concluded that categorical features are experience_level and burnout_risk  
# ordinal
# Stress_Level_1_10
# Code_Complexity_Score  
# numerical
# AI_Tool_Usage_%
# Hours_Coded
# Tasks_Completed
# Current_Burnout_Score
# Target variable
# Burnout_Risk

df['Day'].unique()    
df['Code_Complexity_Score'].value_counts()
# my dataset has 360,000 rows and possible scores are 1-10 , so it tells how many each comes.
df.duplicated().sum()
df.corr(numeric_only=True)
# tells correlation coefficient . how two variables change together.-1 to 1
# Hours_Coded vs Tasks_Completed = 0.790518
# This means: Developers who code more hours complete more tasks.
# This is a strong positive correlation.

,Day,AI_Tool_Usage_%,Hours_Coded,Code_Complexity_Score,Bugs_Introduced,Tasks_Completed,Stress_Level_1_10,Current_Burnout_Score
Day,1.000000,-0.000279,0.000785,0.000680,-0.000181,0.000753,0.000358,0.113404
AI_Tool_Usage_%,-0.000279,1.000000,-0.002747,0.001677,-0.194889,0.478553,-0.097694,-0.090930
Hours_Coded,0.000785,-0.002747,1.000000,0.000898,0.128037,0.790518,0.267115,0.004526
Code_Complexity_Score,0.000680,0.001677,0.000898,1.000000,0.502544,0.001238,0.148694,-0.001228
Bugs_Introduced,-0.000181,-0.194889,0.128037,0.502544,1.000000,-0.201621,0.399523,0.157813
Tasks_Completed,0.000753,0.478553,0.790518,0.001238,-0.201621,1.000000,0.076638,-0.103107
Stress_Level_1_10,0.000358,-0.097694,0.267115,0.148694,0.399523,0.076638,1.000000,0.593168
Current_Burnout_Score,0.113404,-0.090930,0.004526,-0.001228,0.157813,-0.103107,0.593168,1.000000

FIX TYPES , MISSINGVALUES AND DUPLICATES

In [5]:
df.dtypes
# df["Experience_Level"] = df["Experience_Level"].astype("category")
# df["Burnout_Risk"] = df["Burnout_Risk"].astype("category")
df.isnull().sum()

User_ID                  0
Day                      0
Experience_Level         0
AI_Tool_Usage_%          0
Hours_Coded              0
Code_Complexity_Score    0
Bugs_Introduced          0
Tasks_Completed          0
Stress_Level_1_10        0
Current_Burnout_Score    0
Burnout_Risk             0
dtype: int64

EDA

In [6]:
df["Experience_Level"].unique()
# tells unique values it has
df["Experience_Level"].value_counts()

Experience_Level
Junior       140400
Mid-Level    129780
Senior        54900
Tech Lead     34920
Name: count, dtype: int64

In [7]:
df["Burnout_Risk"].unique()

<StringArray>
['High', 'Medium', 'Low']
Length: 3, dtype: str

In [ ]:

# checking if target is balanced
df["Burnout_Risk"].value_counts()
sns.countplot(x="Burnout_Risk", data=df)
plt.title("Burnout Risk Distribution")
plt.show()

In [ ]:
num_cols = df.select_dtypes(include=["int64","float64"]).columns
df[num_cols].hist(figsize=(14,10), bins=30)
plt.show()

In [ ]:
# EDA - correlation heatmap
plt.figure(figsize=(10,8))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap="coolwarm")
plt.show()

OUTLIER - An outlier is a value that is too far from the rest of the data.

In [ ]:
sns.boxplot(x=df["Hours_Coded"])
plt.show()

In [ ]:
# num_cols = df.select_dtypes(include=["int64","float64"]).columns

# for col in num_cols:
#     sns.boxplot(x=df[col])
#     plt.title(col)
#     plt.show()

Skewness tells if the data leans left or right.

In [ ]:
df.skew(numeric_only=True)

In [ ]:
sns.histplot(df["Bugs_Introduced"], kde=True)
plt.show()

ML models work with numbers, not text.
ENCODING

<!-- (Label Encoding) -->

In [ ]:
# (Label Encoding)
df["Experience_Level"] = df["Experience_Level"].map({
    "Junior": 0,
    "Mid-Level": 1,
    "Senior": 2,
    "Tech Lead": 3
})  

df["Burnout_Risk"] = df["Burnout_Risk"].map({
    "Low":0,
    "Medium":1,
    "High":2
})

df.head()

,User_ID,Day,Experience_Level,AI_Tool_Usage_%,Hours_Coded,Code_Complexity_Score,Bugs_Introduced,Tasks_Completed,Stress_Level_1_10,Current_Burnout_Score,Burnout_Risk
0,DEV_0001,1,0,26.7,7.4,5,2,6.98,5,97.0,2
1,DEV_0001,2,0,0.0,11.6,3,2,8.35,6,97.0,2
2,DEV_0001,3,0,18.7,7.7,9,3,7.11,6,97.0,2
3,DEV_0001,4,0,13.0,7.7,7,3,7.10,6,97.0,2
4,DEV_0001,5,0,22.8,7.6,6,3,7.05,6,96.5,2

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 360000 entries, 0 to 359999
Data columns (total 11 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   User_ID                360000 non-null  str
 1   Day                    360000 non-null  int64
 2   Experience_Level       360000 non-null  int64
 3   AI_Tool_Usage_%        360000 non-null  float64
 4   Hours_Coded            360000 non-null  float64
 5   Code_Complexity_Score  360000 non-null  int64
 6   Bugs_Introduced        360000 non-null  int64
 7   Tasks_Completed        360000 non-null  float64
 8   Stress_Level_1_10      360000 non-null  int64
 9   Current_Burnout_Score  360000 non-null  float64
 10  Burnout_Risk           360000 non-null  int64
dtypes: float64(4), int64(6), str(1)
memory usage: 30.2 MB

In [ ]:

df.describe()

,Day,Experience_Level,AI_Tool_Usage_%,Hours_Coded,Code_Complexity_Score,Bugs_Introduced,Tasks_Completed,Stress_Level_1_10,Current_Burnout_Score,Burnout_Risk
count,360000.000000,360000.000000,360000.000000,360000.000000,360000.000000,360000.000000,360000.000000,360000.000000,360000.000000,360000.000000
mean,90.500000,0.956500,44.388950,8.449510,5.491586,2.156347,7.820816,6.788667,64.912709,1.211842
std,51.960795,0.963644,23.326398,1.465926,2.873484,1.129312,0.790077,1.805560,34.800122,0.848512
min,1.000000,0.000000,0.000000,4.000000,1.000000,0.000000,4.400000,1.000000,0.000000,0.000000
25%,45.750000,0.000000,26.700000,7.500000,3.000000,1.000000,7.280000,6.000000,35.600000,0.000000
50%,90.500000,1.000000,43.600000,8.200000,5.000000,2.000000,7.780000,7.000000,73.300000,1.000000
75%,135.250000,1.000000,61.100000,9.200000,8.000000,3.000000,8.350000,8.000000,100.000000,2.000000
max,180.000000,3.000000,100.000000,14.900000,10.000000,7.000000,10.560000,10.000000,100.000000,2.000000

In [12]:
df["Experience_Level"].unique()

array([0, 1, 3, 2])

In [13]:
df["Burnout_Risk"].unique()

array([2, 1, 0])